#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Chạy lint-staged
echo "✅ Running lint-staged..."
yarn lint-staged

if [ $? -ne 0 ]; then
  echo "❌ Lint-staged failed. Aborting commit."
  exit 1
fi

# Build dự án
echo "🔨 Building project..."
yarn build:local

if [ $? -ne 0 ]; then
  echo "❌ Build failed. Aborting commit."
  exit 1
fi

echo "✅ All checks passed. Proceeding with commit."
